### ISSUE TITLE
Remove eval() from formulas

### ISSUE THREAD

**Issue by budnix** [handsontable/formula-parser#18]
It's necessary to replace `eval()` function with another alternatives for security and performance reason. `eval()` function currently is used into formula.js (`COUNTIF`, `COUNTIFS`, `FINDFIELD`, `SUMIF`, `SUMIFS`, `AVERAGEIF`, `AVERAGEIFS`) and into gramma parser (https://github.com/handsontable/formula-parser/blob/develop/src/grammar-parser/grammar-parser.jison#L191)

**Comment by slavabogov** [comment]
The same thing needs to be done with `new Function` call here: https://github.com/handsontable/formula-parser/blob/0df57d6b13710ed6f39ac7fb531b8346d867c8ea/dist/formula-parser.js#L5113-L5115
If there is `Content-Security-Policy: script-src 'self'` header presented, an EvalError occurs

**Comment by wojciechczerniak** [comment]
Blocked by: https://github.com/jstat/jstat/pull/236

**Comment by stephjang** [comment]
jstat doesn't seem to have been updated since Oct 2017. Could the handsontable team fork the jstat repo and merge the [PR that fixes this](https://github.com/jstat/jstat/pull/236) or (preferred) offer a way to unbundle this dependency?

Unfortunately, this issue makes it impossible for many teams, including my own, to adopt handsontable.

**Comment by AMBudnik** [comment]
Hey @stephjang Please read my comment at https://github.com/jstat/jstat/pull/236
we've created a task for the jstat fork but haven't had time to do it yet.

**Comment by budnix** [comment]
The new version of the `formula-parser` has been released which includes a fix for this issue.
